<a href="https://colab.research.google.com/github/AbhishekKaushikCV/PyTorch/blob/main/Introduction_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tutorial 2: Introduction to PyTorch
- PyTorch is an open source machine learning framework that allows you to write your own neural networks and optimize them efficiently

In [ ]:
## Standard libraries
import os
import math
import numpy as np 
import time

## Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline 
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

## Progress bar
from tqdm.notebook import tqdm

### The basics of PyTorch

In [ ]:
import torch
print("Using torch:",torch.__version__)

Using torch: 1.10.0+cu111


In [ ]:
# Set the seed
torch.manual_seed(42)

### Tensors:
- torch.Tensor()
- torch.zeros()
- torch.ones()
- torch.rand()
- torch.randn()
- torch.arange()


In [ ]:
x = torch.Tensor(2,3,4)
print(x)

tensor([[[5.6244e+09, 3.0855e-41, 7.0065e-44, 6.8664e-44],
         [6.3058e-44, 6.8664e-44, 7.0065e-44, 6.3058e-44],
         [7.0065e-44, 7.1466e-44, 1.1771e-43, 6.8664e-44]],

        [[7.0065e-44, 8.1275e-44, 7.0065e-44, 6.7262e-44],
         [8.1275e-44, 6.8664e-44, 7.1466e-44, 6.4460e-44],
         [7.0065e-44, 6.8664e-44, 7.8473e-44, 7.2868e-44]]])


In [ ]:
x = torch.zeros(2,3,4)
print(x)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [ ]:
x = torch.rand(2,3,4)
print(x)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])


In [ ]:
x = torch.randn(2,3,4)
print(x)

tensor([[[ 0.3559, -0.6866, -0.4934,  0.2415],
         [-1.1109,  0.0915, -2.3169, -0.2168],
         [-0.9138, -0.6581,  0.0780,  0.5258]],

        [[-0.4880,  1.1914, -0.8140, -0.7360],
         [-1.4032,  0.0360, -0.0635,  0.6756],
         [-0.0978,  1.8446, -1.1845,  1.3835]]])


In [ ]:
x = torch.arange(1,10)
print(x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
y = x.view(3,3)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
shape=y.shape
print(shape)

torch.Size([3, 3])


In [ ]:
x = torch.Tensor(2,3,4)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

Size: 2 3 4


### Tensor to NumPy and vice-versa

In [ ]:
np_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
tensor = torch.from_numpy(np_arr)
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
arr = tensor.numpy()
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- In case you have a tensor on GPU, you need to call `.cpu()` on the tensor beforehand. Hence, you get a line like `np_arr = tensor.cpu().numpy()`.

### Tensor Operations:


In [ ]:
# Addition
x1 = torch.rand(3,3)
x2 = torch.rand(3,3)
print(x1)
print(x2)
y = x1 + x2
print(y)

tensor([[0.6044, 0.7581, 0.9037],
        [0.9555, 0.1035, 0.6258],
        [0.2849, 0.4452, 0.1258]])
tensor([[0.9554, 0.1330, 0.7672],
        [0.6757, 0.6625, 0.2297],
        [0.9545, 0.6099, 0.5643]])
tensor([[1.5599, 0.8912, 1.6709],
        [1.6312, 0.7660, 0.8555],
        [1.2394, 1.0551, 0.6901]])


In [ ]:
# Inplace addition
x1 = torch.rand(3,3)
x2 = torch.rand(3,3)

print(x1)
print('Before add:',x2)

x2.add_(x1)
print('After add:',x2)

tensor([[0.0594, 0.7099, 0.4250],
        [0.2709, 0.9295, 0.6115],
        [0.2234, 0.2469, 0.4761]])
Before add: tensor([[0.7792, 0.3722, 0.2147],
        [0.3288, 0.1265, 0.6783],
        [0.8870, 0.0293, 0.6161]])
After add: tensor([[0.8386, 1.0821, 0.6397],
        [0.5997, 1.0559, 1.2898],
        [1.1104, 0.2762, 1.0922]])


In [ ]:
# Changing the shape of the tensor
x = torch.arange(6)
print("X:",x)

X: tensor([0, 1, 2, 3, 4, 5])


In [ ]:
x = x.view(2, 3)
print("X", x)
print(x.shape)


X tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])


In [ ]:
# Swapping dimension '0' and '1'
x = x.permute(1,0)
print("X:",x)
print("Swapped axes:",x.shape)

X: tensor([[0, 3],
        [1, 4],
        [2, 5]])
Swapped axes: torch.Size([3, 2])


In [ ]:
# Matrix multiplication
x = torch.arange(6)
x = x.view(2,3)
print("X:",x)

y = torch.arange(6)
y = y.view(3,2)
print("Y:",y)

p = torch.matmul(x,y)
print("Product:",p)



X: tensor([[0, 1, 2],
        [3, 4, 5]])
Y: tensor([[0, 1],
        [2, 3],
        [4, 5]])
Product: tensor([[10, 13],
        [28, 40]])


### Indexing:

In [ ]:
x = torch.arange(12).view(3,4)
print("X:",x)

X: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [ ]:
x[:,]

tensor([1, 5, 9])